Improvements windows installer script
tipi-build/cli pull request #35
Opened 2022-06-13 16:25 UTC by pysco68

- cleaned up messages
- fixed #34
- "fixed" #31 by testing writability and outputting appropriate message to the user
- Added detection for the tipi install folder already being on PATH
- Improved and unified a bunch of messages

2022-06-15 15:15 UTC, pysco68 commented
⚠️ We have to switch the cloud installation to system install before we proceed merging this one ⚠️ 

Otherwise tipi will be installed as user "packer" during installation and won't be available to our user in the end.

2022-06-16 18:40 UTC, daminetreg commented on install/install_for_macos_linux.sh
> +    $INSTALL_FOLDER/bin/tipi --dont-upgrade run echo "Done"
THese changes are also #36. but they are compatible

2022-06-16 18:42 UTC, daminetreg commented on install/install_for_windows.ps1
> +
If I set TIPI_INSTALL_DEST + TIPI_INSTALL_SYSTEM I end up installed in ProgramData nonetheless.

2022-06-16 18:53 UTC, daminetreg requested changes
Great. I'm afraid of the combinatory but looks fine.

- [x] TIPI_INSTALL_DEST not respected in all cases

Regarding the TIPI_INSTALL_DEST that isn't respect when TIPI_INSTALL_SYSTEM is wanted I thinks it's a problem, and I believe can be in the remote environment provisioning.

2022-06-17 07:42 UTC, daminetreg approved these changes

2022-06-17 08:50 UTC, daminetreg approved these changes

2022-06-17 08:50 UTC, merged