New release package format
tipi-build/cli pull request #83
Opened 2024-03-28 00:28 UTC by Lambourl

the aim of this pr is to adapt  install script to new release package format

2024-03-28 04:33 UTC, pysco68 requested changes
This new version will be crashing on releases that do not contain the cmake-re binary.
We should be *at least* backwards-compatible with our prior releases, and perhaps we might want to do  copy of all the binaries in <extracted_location>/bin/ anyway?

2024-03-28 05:57 UTC, Lambourl commented
> This new version will be crashing on releases that do not contain the new binary.
> We should be _at least_ backwards-compatible with our prior releases, and perhaps we might want to do copy of all the binaries in <extracted_location>/bin/ anyway?

You're right, I have made the necessary changes

2024-04-04 18:36 UTC, daminetreg approved these changes

2024-04-04 18:46 UTC, daminetreg commented
My review is actually to do #84 as next step.

2024-04-04 18:46 UTC, merged